In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd


Mounted at /content/drive


In [2]:
df=pd.read_csv("/content/drive/My Drive/train.csv")

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
df=df.dropna()
X=df.drop('label',axis=1)
y=df['label']
# X.shape


In [5]:
X.shape

(18285, 4)

In [6]:
y.shape

(18285,)

In [7]:
import tensorflow as tf

In [8]:
tf.__version__

'2.12.0'

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [10]:
voc_size=5000

In [11]:
messages=X.copy()
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [12]:
messages.reset_index(inplace=True)

In [13]:
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [14]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [15]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [16]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[1704, 4897, 3689, 3328, 1775, 2195, 3347, 163, 4127, 1500],
 [135, 1961, 2998, 4395, 2400, 4402, 191],
 [2578, 1381, 2617, 398],
 [665, 3094, 1606, 1770, 2699, 2545],
 [4415, 2400, 2140, 4846, 623, 4206, 2400, 3633, 3829, 4448],
 [3181,
  3709,
  4244,
  4115,
  2872,
  4539,
  3681,
  4663,
  2447,
  1897,
  4430,
  3533,
  3363,
  723,
  191],
 [2987, 819, 4692, 1008, 282, 2197, 2709, 1785, 213, 2955, 4301],
 [297, 789, 3400, 1760, 796, 4756, 4539, 2959, 213, 2955, 4301],
 [609, 3236, 4780, 649, 1130, 2518, 3445, 4201, 4539, 4805],
 [511, 4810, 4647, 4125, 1618, 3742, 2020, 4660],
 [2758, 2423, 4166, 2138, 3461, 3836, 4090, 2418, 1063, 3059, 1274],
 [1770, 4095, 1775, 2518, 4539, 796],
 [2465, 4019, 1952, 968, 3782, 3053, 1845, 1532, 3240],
 [3308, 4453, 486, 213, 1819, 196, 1977, 213, 2955, 4301],
 [3167, 3675, 3575, 646, 1160, 213, 2955, 4301],
 [1283, 1216, 2436, 189, 3420, 1578, 100, 3718, 4015, 2628],
 [3171, 919, 1961],
 [1697, 356, 750, 450, 4539, 3250, 3332, 191],
 [2155, 4

In [17]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  163 4127 1500]
 [   0    0    0 ... 2400 4402  191]
 [   0    0    0 ... 1381 2617  398]
 ...
 [   0    0    0 ...  213 2955 4301]
 [   0    0    0 ... 1656  541 2983]
 [   0    0    0 ... 4446 1463 1484]]


In [18]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1704,
       4897, 3689, 3328, 1775, 2195, 3347,  163, 4127, 1500], dtype=int32)

In [19]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [20]:
len(embedded_docs),y.shape

(18285, (18285,))

In [21]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [22]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [24]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 13s 51ms/step - loss: 0.3415 - accuracy: 0.8358 - val_loss: 0.1960 - val_accuracy: 0.9153
Epoch 2/10
192/192 [==============================] - 10s 53ms/step - loss: 0.1401 - accuracy: 0.9456 - val_loss: 0.1998 - val_accuracy: 0.9221
Epoch 3/10
192/192 [==============================] - 8s 41ms/step - loss: 0.1011 - accuracy: 0.9630 - val_loss: 0.2211 - val_accuracy: 0.9195
Epoch 4/10
192/192 [==============================] - 10s 53ms/step - loss: 0.0759 - accuracy: 0.9740 - val_loss: 0.2580 - val_accuracy: 0.9135
Epoch 5/10
192/192 [==============================] - 11s 56ms/step - loss: 0.0607 - accuracy: 0.9793 - val_loss: 0.3341 - val_accuracy: 0.9017
Epoch 6/10
192/192 [==============================] - 8s 40ms/step - loss: 0.0513 - accuracy: 0.9829 - val_loss: 0.3019 - val_accuracy: 0.9114
Epoch 7/10
192/192 [==============================] - 10s 54ms/step - loss: 0.0372 - accuracy: 0.9887 - val_loss: 0.4048 - val_accuracy: 0

In [25]:
y_pred=model.predict(X_test)
y_pred

189/189 [==============================] - 2s 8ms/step


array([[9.9992937e-01],
       [1.0713238e-08],
       [9.1581031e-05],
       ...,
       [2.4550124e-03],
       [9.9718481e-01],
       [9.9992490e-01]], dtype=float32)

In [26]:
y_pred=np.where(y_pred>0.5,1,0)

In [27]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[3110,  309],
       [ 259, 2357]])

In [28]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9058823529411765

In [29]:
from tensorflow.keras.layers import Dropout
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [30]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 13s 54ms/step - loss: 0.3351 - accuracy: 0.8445 - val_loss: 0.2038 - val_accuracy: 0.9130
Epoch 2/10
192/192 [==============================] - 8s 42ms/step - loss: 0.1468 - accuracy: 0.9429 - val_loss: 0.1919 - val_accuracy: 0.9198
Epoch 3/10
192/192 [==============================] - 10s 54ms/step - loss: 0.1052 - accuracy: 0.9613 - val_loss: 0.2031 - val_accuracy: 0.9205
Epoch 4/10
192/192 [==============================] - 10s 54ms/step - loss: 0.0773 - accuracy: 0.9722 - val_loss: 0.2252 - val_accuracy: 0.9213
Epoch 5/10
192/192 [==============================] - 8s 41ms/step - loss: 0.0574 - accuracy: 0.9815 - val_loss: 0.2623 - val_accuracy: 0.9138
Epoch 6/10
192/192 [==============================] - 10s 54ms/step - loss: 0.0397 - accuracy: 0.9870 - val_loss: 0.2847 - val_accuracy: 0.9171
Epoch 7/10
192/192 [==============================] - 9s 46ms/step - loss: 0.0304 - accuracy: 0.9898 - val_loss: 0.3511 - val_accuracy: 0.

In [31]:
y_pred=model.predict(X_test)
y_pred=np.where(y_pred>0.5,1,0)
accuracy_score(y_test,y_pred)

189/189 [==============================] - 2s 9ms/step


0.9148301574150787